sudo: false

language: node_js

matrix:
  include:
    - node_js: 'node'
      env: NPM_AUDIT=yes NPM_PACK=yes
    - node_js: '10'
    - node_js: '8'

install:
  - set -e
  - npm install
  - if [ "$NPM_AUDIT" = true ]; then npm audit; fi

script:
  - if [ -n "$NPM_PACK" ]; then npm pack; fi
  - npm run test:spec
  - git diff --stat --exit-code
  - for f in $(git ls-files --others --exclude-standard); do git diff --no-index --stat --exit-code /dev/null $next; done
  - npm run clean
