sudo: false

language: node_js

matrix:
  include:
    - node_js: 'node'
      env: NPM_AUDIT=true
    - node_js: '10'
    - node_js: '8'

install:
  - npm install
  - if [ "$NPM_AUDIT" = true ]; then npm audit; fi

script:
  - npm run test
  - npm run clean
  - git add .
  - git diff-index --quiet HEAD
